### ISSUE TITLE
Swap in array

### ISSUE THREAD

**Issue by AnandDasani2670** [AnandDasani2670/AD-Hacktoberfest#20]
### Discription 

Write a program to swap in array

**Comment by Onkar627** [comment]
@AnandDasani2670 can you assign me this task

**Comment by AnandDasani2670** [comment]
@Onkar627  yes go ahead

**Comment by Zafeer-R** [comment]
I also want to work on this issue 
Can you please assign this to me

**Comment by manish866** [comment]
Please assign me I will do it in java

**Comment by hasan8130** [comment]
Hey, @AnandDasani2670  can u please assign me this issue under hactoberfest'21.

**Comment by abhijeet-crypto** [comment]
i would like to work on this @AnandDasani2670

**Comment by luharuka** [comment]
@AnandDasani2670 please assign it to me.

**Comment by Hasindu5512** [comment]
@AnandDasani2670  Could you please assign me this project?
