### ISSUE TITLE
To Find Factorial of a Number(Java)

### ISSUE THREAD

**Issue by manvikri22** [AnandDasani2670/AD-Hacktoberfest#32]
Hacktoberfest2021

**Comment by manvikri22** [comment]
Can i work on this issue for hacktoberfest2021??

**Comment by Zafeer-R** [comment]
Please assign this issue to me

**Comment by Shubham56-droid** [comment]
i would like to work on the issue pls assign the issue to me.

**Comment by manish866** [comment]
Please assign me I will do it in java
